--Duplicates handling,selecting transactions with duplicate appontments
Select APPOINTMENT_ID, COUNT(APPOINTMENT_ID)
FROM STAGING_TABLE
GROUP BY APPOINTMENT_ID
HAVING COUNT(APPOINTMENT_ID) > 1;

--join non duplicated tables for further analysis
Select p.*,a.APPOINTMENT_ID,a.APPOINTMENT_DATE,a.DOCTOR,a.STATUS
From NON_DUBLICATED p
FULL JOIN NON_DUPLICATED_APPOINTMENTS a
ON p.PATIENT_ID = a.PATIENT_ID
HAVING APPOINTMENT_ID IS NOT NULL AND APPOINTMENT_DATE IS NOT NULL;

--Standardize string columns
UPDATE PATIENTS_APPOINTMENTS
SET NAME = UPPER(TRIM(NAME)), GENDER = UPPER(GENDER),STATUS = UPPER(STATUS),CITY = UPPER(CITY);

-- standardize date formats
UPDATE PATIENTS_APPOINTMENTS 
SET DOB = COALESCE(
TRY_TO_DATE(DOB,'YYYY-MM-DD'), TRY_TO_DATE(DOB,'DD-MM-YYYY'),TRY_TO_DATE(DOB,'MM-DD-YYYY')
,TRY_TO_DATE(DOB,'YYYY/MM/DD'),TRY_TO_DATE(DOB,'DD/MM/YYYY'),TRY_TO_DATE(DOB,'MM/DD/YYYY')
)
;

--create and flag patients with no appointment dates for further analysis
Select p.*,a.APPOINTMENT_ID,a.APPOINTMENT_DATE,a.DOCTOR,a.STATUS
From NON_DUBLICATED p
FULL JOIN NON_DUPLICATED_APPOINTMENTS a
ON p.PATIENT_ID = a.PATIENT_ID
HAVING APPOINTMENT_ID IS  NULL AND APPOINTMENT_DATE IS  NULL;

