--create Doctor workload table tracking appointments status
CREATE TABLE DOCTOR_APPOINTMENT_STATUS_RANKING AS 
SELECT DOCTOR,STATUS_COUNT,APPOINTMENTS_DOCTOR, RANK() OVER (PARTITION BY DOCTOR ORDER BY APPOINTMENTS_DOCTOR DESC) AS RANK
FROM APPOINTMENT_STATUS_DOCTOR;

-- create table tracking the number of appointments made per month
CREATE TABLE APPOINTMENTS_MONTH AS
SELECT EXTRACT(MONTH,APPOINTMENT_DATE) AS MONTH, COUNT(PATIENT_ID) AS NUMBER_PATIENTS
FROM PATIENTS_APPOINTMENTS
WHERE APPOINTMENT_DATE IS NOT NULL
GROUP BY EXTRACT(MONTH,APPOINTMENT_DATE)
ORDER BY EXTRACT(MONTH,APPOINTMENT_DATE);

--display number of patients with more than one booking,non-duplicated
Select PATIENT_ID,COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM PATIENTS_APPOINTMENTS
GROUP BY PATIENT_ID
HAVING COUNT(APPOINTMENT_ID) > 1
ORDER BY COUNT(APPOINTMENT_ID) DESC;

--Track Patients with more than one cancelled appointment
CREATE TABLE CANCELLED_APPOINTMENTS AS
Select PATIENT_ID,COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,COALESCE(STATUS,'UNKHOWN') AS STATUS
FROM PATIENTS_APPOINTMENTS
WHERE STATUS  = 'CANCELLED'
GROUP BY PATIENT_ID,COALESCE(STATUS,'UNKHOWN')
HAVING COUNT(APPOINTMENT_ID) > 1
ORDER BY PATIENT_ID;

--tracking registered patients that never got an appointment date
Select p.*,a.APPOINTMENT_ID,a.APPOINTMENT_DATE,a.DOCTOR,a.STATUS
From NON_DUBLICATED p
FULL JOIN NON_DUPLICATED_APPOINTMENTS a
ON p.PATIENT_ID = a.PATIENT_ID
HAVING APPOINTMENT_ID IS  NULL AND APPOINTMENT_DATE IS  NULL;

--tables and results exported as .csv via download on Snowsight UI for dashboarding and reporting
